import { Socket } from 'socket.io';
import { socketCore } from './socket-core';
import { FreeMessage } from '../../types/free.types';
import type { ChatMessage, ChatRoom } from '@/lib/ai/chatService';
import { SendMessageData } from '../../types/common.types';
import chatRoomDB from '@/lib/db/chatRoomDB';
import { API_BASE_URL } from '@/lib/api/baseUrl';
import { loggers } from '@/utils/logger';

export class FreeSocketServer {
  
  // Free
  registerHandlers(socket: Socket): void {
    socket.removeAllListeners('send-message');
    socket.removeAllListeners('auto-conversation-start');
    socket.removeAllListeners('auto-conversation-stop');
    
    loggers.socket.info(`🔧 [FREE] Registering fresh handlers for socket ${socket.id}`);
    
    socket.on('send-message', (data: SendMessageData) => this.handleSendMessage(socket, data));
    
    socket.on('auto-conversation-start', (data) => this.handleAutoConversationStart(socket, data));
    socket.on('auto-conversation-stop', (data) => this.handleAutoConversationStop(socket, data));
    
    loggers.socket.info(`✅ [FREE] Handlers registered for socket ${socket.id}`);
  }

  private async handleSendMessage(socket: Socket, data: SendMessageData): Promise<void> {
    try {
      const roomId = String(data.roomId);
      const messageText = typeof data.message === 'string' ? data.message : data.message;

      const message: FreeMessage = {
        id: `user-${Date.now()}`,
        text: messageText,
        sender: data.sender,
        senderType: 'user',
        isUser: true,
        timestamp: new Date(),
        metadata: {
          conversationId: roomId
        }
      };

      loggers.socket.info(`💬 [FREE] Message from ${data.sender} in room ${roomId}: ${messageText.substring(0, 50)}...`);

      try {
        const dbMessage: ChatMessage = { ...message, timestamp: message.timestamp as Date };
        await chatRoomDB.addMessage(roomId, dbMessage);
        loggers.socket.info(`✅ [FREE] Message saved to MongoDB: ${message.id}`);
      } catch (dbError) {
        loggers.socket.error('[FREE] MongoDB save error:', dbError);
      }

      socket.broadcast.to(roomId).emit('new-message', {
        roomId: roomId,
        message: message
      });
      loggers.socket.info(`📢 [FREE] Message broadcasted to room ${roomId}`);

      if (message.isUser) {
        await this.generateAIResponse(roomId, message);
      }

    } catch (error) {
      loggers.socket.error('❌ [FREE] Send message error:', error);
      socket.emit('error', { message: 'Failed to send message' });
    }
  }

  private async generateAIResponse(roomId: string, userMessage: FreeMessage): Promise<void> {
    try {
      loggers.socket.info(`🤖 [FREE] Generating AI response for room ${roomId}`);

      const room = await chatRoomDB.getChatRoomById(roomId);
      if (!room) {
        loggers.socket.error(`❌ [FREE] Room not found: ${roomId}`);
        return;
      }

      const isAutoActive = await this.checkAutoConversationStatus(roomId);
      if (isAutoActive) {
        loggers.socket.info(`🔍 [FREE] Auto conversation active - skipping manual AI response`);
        return;
      }

      // Python AI
      const response = await this.requestAIResponse(roomId, userMessage, room);
      if (response) {
        socketCore.broadcastToRoom(roomId, 'new-message', {
          roomId: roomId,
          message: response
        });
        loggers.socket.info(`✅ [FREE] AI response broadcasted to room ${roomId}`);
      }

    } catch (error) {
      loggers.socket.error('❌ [FREE] AI response generation error:', error);
    }
  }

  // Python AI
  private async requestAIResponse(roomId: string, userMessage: FreeMessage, room: ChatRoom): Promise<FreeMessage | null> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/chat/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          room_id: roomId,
          user_message: userMessage.text,
          npcs: room?.participants?.npcs || [],
          topic: room?.title,
          context: room?.context,
          llm_provider: 'openai',
          llm_model: 'gpt-4o',
          api_key: process.env.OPENAI_API_KEY
        }),
      });

      if (!response.ok) {
        throw new Error(`Python API error: ${response.status}`);
      }

      const responseData = await response.json();
      if (responseData && responseData.response && responseData.philosopher) {
        const aiMessage: FreeMessage = {
          id: `ai-${Date.now()}`,
          text: responseData.response,
          sender: responseData.philosopher,
          senderType: 'npc',
          isUser: false,
          timestamp: new Date(),
          metadata: {
            isAutoGenerated: false,
            conversationId: roomId,
            ...responseData.metadata
          },
          citations: responseData.citations || []
        };

        // MongoDB AI
        const dbMessage: ChatMessage = { ...aiMessage, timestamp: aiMessage.timestamp as Date };
        await chatRoomDB.addMessage(roomId, dbMessage);
        return aiMessage;
      }

      return null;
    } catch (error) {
      loggers.socket.error('❌ [FREE] Python API request failed:', error);
      return null;
    }
  }

  private async checkAutoConversationStatus(roomId: string): Promise<boolean> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/auto-conversation/status?room_id=${roomId}`);
      if (response.ok) {
        const data = await response.json();
        return data.active === true;
      }
    } catch (error) {
      loggers.socket.error('❌ [FREE] Auto conversation status check failed:', error);
    }
    return false;
  }

  private async handleAutoConversationStart(socket: Socket, data: { roomId: string; npcs: string[] }): Promise<void> {
    try {
      loggers.socket.info(`🔄 [FREE] Starting auto conversation in room ${data.roomId}`);
      
      // Python
      const response = await fetch(`${API_BASE_URL}/api/auto-conversation`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          room_id: data.roomId,
          npcs: data.npcs
        })
      });

      if (response.ok) {
        socketCore.broadcastToRoom(data.roomId, 'auto-conversation-status', {
          roomId: data.roomId,
          isActive: true
        });
        loggers.socket.info(`✅ [FREE] Auto conversation started in room ${data.roomId}`);
      }
    } catch (error) {
      loggers.socket.error('❌ [FREE] Auto conversation start failed:', error);
    }
  }

  private async handleAutoConversationStop(socket: Socket, data: { roomId: string }): Promise<void> {
    try {
      loggers.socket.info(`⏹️ [FREE] Stopping auto conversation in room ${data.roomId}`);
      
      const response = await fetch(`${API_BASE_URL}/api/auto-conversation`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ room_id: data.roomId })
      });

      if (response.ok) {
        socketCore.broadcastToRoom(data.roomId, 'auto-conversation-status', {
          roomId: data.roomId,
          isActive: false
        });
        loggers.socket.info(`✅ [FREE] Auto conversation stopped in room ${data.roomId}`);
      }
    } catch (error) {
      loggers.socket.error('❌ [FREE] Auto conversation stop failed:', error);
    }
  }
}

export const freeSocketServer = new FreeSocketServer(); 