import { BaseMessage, BaseRoom, SocketEvents } from './common.types';

// Free 채팅 메시지 타입
export interface FreeMessage extends BaseMessage {
  metadata?: {
    isAutoGenerated?: boolean;
    conversationId?: string;
  };
}

// Free 채팅방 타입
export interface FreeRoom extends BaseRoom {
  dialogueType: 'free';
  autoConversation?: {
    isActive: boolean;
    lastActivity: Date;
    participants: string[];
  };
}

// Free 채팅 소켓 이벤트
export interface FreeSocketEvents extends SocketEvents {
  // Auto conversation 관련
  'auto-conversation-start': (data: { roomId: string; npcs: string[] }) => void;
  'auto-conversation-stop': (data: { roomId: string }) => void;
  'auto-conversation-status': (data: { roomId: string; isActive: boolean }) => void;
  
  // AI 응답 관련
  'ai-thinking': (data: { roomId: string; npcId: string }) => void;
  'ai-response': (data: { roomId: string; message: FreeMessage }) => void;
}

// Free 채팅 설정
export interface FreeConversationConfig {
  roomId: string;
  npcs: string[];
  topic?: string;
  context?: string;
  autoReplyInterval?: number;
  maxAutoMessages?: number;
} 