import { BaseMessage, BaseRoom, SocketEvents } from './common.types';

// Free
export interface FreeMessage extends BaseMessage {
  metadata?: {
    isAutoGenerated?: boolean;
    conversationId?: string;
  };
}

// Free
export interface FreeRoom extends BaseRoom {
  dialogueType: 'free';
  autoConversation?: {
    isActive: boolean;
    lastActivity: Date;
    participants: string[];
  };
}

// Free
export interface FreeSocketEvents extends SocketEvents {
  // Auto conversation
  'auto-conversation-start': (data: { roomId: string; npcs: string[] }) => void;
  'auto-conversation-stop': (data: { roomId: string }) => void;
  'auto-conversation-status': (data: { roomId: string; isActive: boolean }) => void;
  
  'ai-thinking': (data: { roomId: string; npcId: string }) => void;
  'ai-response': (data: { roomId: string; message: FreeMessage }) => void;
}

// Free
export interface FreeConversationConfig {
  roomId: string;
  npcs: string[];
  topic?: string;
  context?: string;
  autoReplyInterval?: number;
  maxAutoMessages?: number;
} 